INSERT INTO Skills VALUES ('Kshitiz' , 'Dart' , 'Flutter' , '1.5 years');
INSERT INTO Skills VALUES ('Mayank' , 'React' , 'JavaScript' , '1 year');
INSERT INTO Skills VALUES ('Ishaan' , 'Node JS' , 'JavaScript' , '1 year');
INSERT INTO Skills VALUES ('Himalaya' , 'ML' , 'Python' , '1.5 years');
INSERT INTO Skills VALUES ('Gaurav' , 'Android' , 'Kotlin' , '1.5 years');
INSERT INTO Skills VALUES ('Dhairya' , 'Swift' , 'C#' , '1.5 years');
INSERT INTO Skills VALUES ('Lakshay' , 'Cyber Security' , 'Python' , '1 years');
INSERT INTO Skills VALUES ('Harsh' , 'Chemical' , 'Drugs' , '2 years');
INSERT INTO Skills VALUES ('Madhvan' , 'React' , 'Javascript' , '1.5 years');

INSERT INTO Education VALUES ('Kshitiz' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education VALUES ('Harsh' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education VALUES ('Sushant' , 'Bal Bharati Public School' , 'IIIT Delhi');
INSERT INTO Education VALUES ('Mihir' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education VALUES ('Apoorv' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education VALUES ('Shivam' , 'Bal Bharati Public School' , 'IIT Delhi');
INSERT INTO Education VALUES ('Sidharth' , 'Bal Bharati Public School' , 'IIT Delhi');
INSERT INTO Education VALUES ('Mayank' , 'Only Boys School' , 'DTU');
INSERT INTO Education VALUES ('Himalaya' , 'Delhi Police School' , 'DTU');
INSERT INTO Education VALUES ('Ishaan' , 'Open School' , 'DTU');
INSERT INTO Education VALUES ('Gaurav' , 'Chhapri School' , 'DTU');