INSERT INTO Skills(name,language,framework,experience) VALUES ('Kshitiz' , 'Dart' , 'Flutter' , '1.5 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Mayank' , 'React' , 'JavaScript' , '1 year');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Ishaan' , 'Node JS' , 'JavaScript' , '1 year');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Himalaya' , 'ML' , 'Python' , '1.5 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Gaurav' , 'Android' , 'Kotlin' , '1.5 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Dhairya' , 'Swift' , 'C#' , '1.5 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Lakshay' , 'Cyber Security' , 'Python' , '1 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Harsh' , 'Chemical' , 'Drugs' , '2 years');
INSERT INTO Skills(name,language,framework,experience) VALUES ('Madhvan' , 'React' , 'Javascript' , '1.5 years');

INSERT INTO Education(Name , School , College) VALUES ('Kshitiz' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Harsh' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Sushant' , 'Bal Bharati Public School' , 'IIIT Delhi');
INSERT INTO Education(Name , School , College) VALUES ('Mihir' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Apoorv' , 'Bal Bharati Public School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Shivam' , 'Bal Bharati Public School' , 'IIT Delhi');
INSERT INTO Education(Name , School , College) VALUES ('Sidharth' , 'Bal Bharati Public School' , 'IIT Delhi');
INSERT INTO Education(Name , School , College) VALUES ('Mayank' , 'Only Boys School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Himalaya' , 'Delhi Police School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Ishaan' , 'Open School' , 'DTU');
INSERT INTO Education(Name , School , College) VALUES ('Gaurav' , 'Chhapri School' , 'DTU');